services:
  evaluator:
    build: ./eval
    ports:
      - "2137:2137"
    networks:
      - stos-net
  
  worker:
    build: ./worker
    networks:
      - stos-net
    environment:
      - LOG_HOST=logstash-logstash
      - LOG_PORT=5228
networks:
  stos-net:
