services:
  evaluator:
    build: ./eval
    ports:
      - "2137:2137"
    networks:
      - stos-net
  
  worker:
    build: ./worker
    networks:
      - stos-net
    environment:
      - LOG_HOST=http://logstash01
      - LOG_PORT=9601
networks:
  stos-net:
